- hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "Hello World"

    - pause:
        seconds: "{{ pause | default(0) | int }}"

    - fail:
      when: fail | default(false) | bool
