- name: Config Manage Platform
  hosts: tower
  gather_facts: false
  run_once: true  # need this when you change localhost to the tower group
  tasks:
    - name: Install pip
      package:
        name: python-pip

    - name: Install Ansible Tower CLI
      pip:
        name: ansible-tower-cli
        state: latest

    - name: Build core configurations
      include_role:
        name: ansible-tower-config

    - name: Install Mid Server
      include_role:
        name: ansible-role-mid
